# Generated by Django 5.2.13 on 2026-04-22 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('department_head', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.RemoveField(
            model_name='team',
            name='department_id',
        ),
        migrations.AddField(
            model_name='team',
            name='department',
            field=models.ForeignKey(db_column='department_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='main.department'),
            preserve_default=False,
        ),
    ]
