# Generated by Django 5.2.13 on 2026-04-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_department_remove_team_department_id_team_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
