# Generated by Django 5.2.13 on 2026-04-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_user_first_name_remove_user_last_name_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('date_created', models.DateField()),
                ('team_mission', models.TextField(blank=True, null=True)),
                ('team_description', models.TextField(blank=True, null=True)),
                ('team_status', models.CharField(max_length=30)),
                ('department_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Team',
            },
        ),
    ]
